// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyuviidkhpzmwfprqwpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5dXZpaWRraHB6bXdmcHJxd3BwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1ODAyNTQsImV4cCI6MjA2OTE1NjI1NH0.-6kt-jWuNoG5ICM4u3CDZeCjaWTQ5g1wBH8kheaTPPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});